const INVALID_ACCESS_TOKEN = 'INVALID ACCESS TOKEN';
const INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR';
const UNAUTHORIZE_USER = 'UNAUTHORIZE USER';

module.exports = {
	INVALID_ACCESS_TOKEN,
	INTERNAL_SERVER_ERROR,
	UNAUTHORIZE_USER
};